name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbooks
      uses: ansible/ansible-lint-action@818251b0717eb7925652556b7962c98dfdaea1e4
      with:
        targets: "room-assistant.yml"
